language: node_js
node_js:
  - "7.2.1"

sudo: required
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
env:
  - CXX=g++-4.8

notifications:
  email:
    on_success: never
    on_failure: always

before_script:
  - npm run build
  - npm run cert