language: node_js
node_js:
  - "7.2.1"
sudo: required
before_script:
  - npm install
  - npm run build
  - npm run cert
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
env:
  - CXX=g++-4.8